"""The release this plugin build is pinned to. Specification section 7.6.

``release-core.json`` is generated by the release process and committed with
the plugin. It is the plugin's only opinion about which Techtree version,
engine, catalog, and founder Skills belong together, and it is verified every
time the plugin loads.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from .constants import PLUGIN_ROOT, RELEASE_CORE_FILENAME
from .models import ReleaseCore, parse_release_core


def load_embedded_release_core(root: Path = PLUGIN_ROOT) -> ReleaseCore:
    """Read and verify the exact ``release-core.json`` bytes shipped here."""
    return parse_release_core((root / RELEASE_CORE_FILENAME).read_bytes())


def canonical_release_core_bytes(core: ReleaseCore) -> bytes:
    """Return the canonical byte form the release digest is taken over.

    The form is RFC 8785 canonical JSON. Every value in this schema is a
    string and every key is ASCII, so sorted keys with no insignificant
    whitespace is exactly that canonical serialization, and the plugin can
    produce it without a serialization dependency.
    """
    return json.dumps(
        core.to_dict(), sort_keys=True, separators=(",", ":"), ensure_ascii=False
    ).encode("utf-8")


def release_core_digest(core: ReleaseCore) -> str:
    """Calculate the canonical digest of a release."""
    return f"sha256:{hashlib.sha256(canonical_release_core_bytes(core)).hexdigest()}"
