"""The release this plugin build is pinned to. Specification sections 6.6, 7.6.

``release-core.json`` is generated by Techtree's release tooling and copied
verbatim into this repository, into the CLI wheel, and into the website's
bootstrap wrapper. All three carry the same bytes, and the digest they are
published under is the SHA-256 of the file exactly as stored — not of a
re-serialized object — so anyone can check it with `shasum` in any of the three
repositories, in any language.

That only works if the file has one spelling. Techtree's release tooling owns
it: keys sorted, two-space indent, no ASCII escaping, one trailing newline.
This module can reproduce that spelling, which is how it detects a file that
has been hand-edited into a different one — whitespace that changes nothing
still changes the digest, and that has to be reported rather than tolerated.

Verification of what the release *claims* stays in Techtree, where
`techtree release verify` checks each coordinate against the thing it names.
The plugin's job is narrower and stated in section 7.6: prove that the CLI
installed on this machine belongs to the same release as this plugin build.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Final

from ..services.models import ReleaseCore, parse_release_core
from .constants import PLUGIN_ROOT, RELEASE_CORE_FILENAME
from .errors import CODE_PLUGIN_RELEASE_CORE_INVALID, PluginError

# Mismatch codes ---------------------------------------------------------------
# Returned rather than raised: a caller reports every disagreement it found at
# once, instead of the first one.

MISMATCH_RELEASE_CORE_DIGEST: Final = "release_core_digest"
MISMATCH_RELEASE_ID: Final = "release_id"
MISMATCH_CLI_VERSION: Final = "cli_version"
MISMATCH_PROTOCOL_VERSION: Final = "protocol_version"
MISMATCH_ENGINE_DIGEST: Final = "engine_digest"
MISMATCH_CATALOG_DIGEST: Final = "catalog_digest"
MISMATCH_INTRO_CLIMB_REFERENCE: Final = "intro_climb_reference"
MISMATCH_PLUGIN_COMMIT: Final = "plugin_commit"
MISMATCH_PLUGIN_REPOSITORY: Final = "plugin_repository"
MISMATCH_INSTALLED_FACTS_MISSING: Final = "installed_release_facts_missing"

#: The coordinates `techtree release info` reports that the plugin also holds.
#: The command reports a subset of the release document plus one coordinate
#: that is not in it at all — the commit stamped into the installed wheel — so
#: the comparison is over exactly this overlap and no more.
_SHARED_COORDINATES: Final = (
    (MISMATCH_RELEASE_ID, "release_id"),
    (MISMATCH_CLI_VERSION, "cli_version"),
    (MISMATCH_PROTOCOL_VERSION, "protocol_version"),
    (MISMATCH_ENGINE_DIGEST, "engine_digest"),
    (MISMATCH_CATALOG_DIGEST, "catalog_digest"),
    (MISMATCH_INTRO_CLIMB_REFERENCE, "intro_climb_reference"),
)


def load_embedded_release_core(root: Path = PLUGIN_ROOT) -> ReleaseCore:
    """Read and verify the exact ``release-core.json`` bytes shipped here.

    Raises:
        PluginError: when the file is missing, invalid, or no longer in the one
            published spelling.
    """
    raw = (root / RELEASE_CORE_FILENAME).read_bytes()
    core = parse_release_core(raw)
    if not is_canonical_document(raw):
        raise PluginError(
            f"{RELEASE_CORE_FILENAME} is not in the one published spelling, so "
            "its digest cannot be the digest the release published",
            code=CODE_PLUGIN_RELEASE_CORE_INVALID,
            repair="Restore the file from the release, never by hand.",
        )
    return core


def render_release_core(core: ReleaseCore) -> bytes:
    """Return the one byte spelling of a release document."""
    text = json.dumps(core.to_dict(), indent=2, sort_keys=True, ensure_ascii=False)
    return f"{text}\n".encode()


def is_canonical_document(raw: bytes) -> bool:
    """Return whether these bytes are already in the one stored spelling."""
    try:
        payload = json.loads(raw)
    except ValueError:
        return False
    if not isinstance(payload, dict):
        return False
    text = json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False)
    return f"{text}\n".encode() == raw


def document_digest(raw: bytes) -> str:
    """Return the digest a release document is published under."""
    return f"sha256:{hashlib.sha256(raw).hexdigest()}"


def release_core_digest(core: ReleaseCore) -> str:
    """Calculate the canonical digest of a release."""
    return document_digest(render_release_core(core))


def embedded_release_core_digest(root: Path = PLUGIN_ROOT) -> str:
    """Return the digest of the release bytes stored in this checkout."""
    return document_digest((root / RELEASE_CORE_FILENAME).read_bytes())


def compare_cli_release(
    embedded: ReleaseCore, installed: Mapping[str, Any]
) -> list[str]:
    """Return mismatch codes between this build and an installed CLI.

    ``installed`` is the ``data`` payload of ``techtree release info``, which
    reports the release digest and the coordinates a CLI can answer for. Empty
    means the two belong to the same release.
    """
    if not installed:
        return [MISMATCH_INSTALLED_FACTS_MISSING]

    mismatches: list[str] = []
    if installed.get("release_core_digest") != release_core_digest(embedded):
        mismatches.append(MISMATCH_RELEASE_CORE_DIGEST)

    if any(field not in installed for _, field in _SHARED_COORDINATES):
        mismatches.append(MISMATCH_INSTALLED_FACTS_MISSING)

    mismatches.extend(
        code
        for code, field in _SHARED_COORDINATES
        if field in installed and installed[field] != getattr(embedded, field)
    )
    return mismatches


def compare_bootstrap_release(
    core: ReleaseCore,
    bootstrap: Mapping[str, Any],
    installed_plugin_commit: str | None,
) -> list[str]:
    """Verify a website release points at this core and this plugin revision.

    The website publishes a read-only ``BootstrapRelease`` that wraps a
    ReleaseCore digest with the coordinates that only exist once the wheel and
    the plugin commit do. The plugin never trusts it in place of its own
    embedded bytes; it only checks that the three repositories agree.
    """
    mismatches: list[str] = []

    if bootstrap.get("release_core_digest") != release_core_digest(core):
        mismatches.append(MISMATCH_RELEASE_CORE_DIGEST)
    if bootstrap.get("cli_version") != core.cli_version:
        mismatches.append(MISMATCH_CLI_VERSION)
    if bootstrap.get("plugin_repository") in (None, ""):
        mismatches.append(MISMATCH_PLUGIN_REPOSITORY)

    published_commit = bootstrap.get("plugin_commit")
    if installed_plugin_commit is not None and published_commit != (
        installed_plugin_commit
    ):
        mismatches.append(MISMATCH_PLUGIN_COMMIT)

    return mismatches
